spring.application.name=ms-notificaciones
server.port=8085

spring.datasource.url=jdbc:postgresql://db.chxavcfzhsifgskhhrkh.supabase.co:5432/postgres
spring.datasource.username=postgres.chxavcfzhsifgskhhrkh
spring.datasource.password=019f5e72-efde-7eb5-bcd3-999e2dc610f8
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8081/oauth2/jwks

eureka.client.service-url.defaultZone=http://127.0.0.1:8761/eureka/
eureka.instance.prefer-ip-address=true
